
###
GET http://localhost:4000/api/jobs

###
GET http://localhost:4000/api/jobs/1/signals

###
GET http://localhost:4000/api/jobs/1/queue


###
GET https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/4448669665